jasypt.encryptor.password: '${BOT_SECRET_ENCRYPTION_KEY}'
bot:
  name: 'Sylphiette'
  token: 'ENC(u9Y1NIt7auK4iJK53SNtB5FHgZ5WZQml9d6td64rdvAGm9G6QEyc6lDbZ8uzsA+Zdv9VqO0lYfpzO4RBeQ5oLn/EoFW/zRvsU+UG1HpmsYlldW7orUoY/VM8WYMMYSWeH8hlIlibBZKfwRH2RodhVw==)'
  id: '1164573836721787061'
  author-id: '469189070380072962'
  default-locale: "ru"
chat-gpt:
  url: 'https://api.openai.com/v1/chat/completions'
  model: 'gpt-3.5-turbo'
  key: 'ENC(ZgOvkWUk4KhT3IgWw2RJyImocVvM3JjvQioza1s4+dTWaTrOWzPq24uVgaNu5hN2IMh9hD9ohUUBBUiuf2EYXOLJd66SDaE20JShgpZdtJvak+9+1BzZA+v7vDlo0Dm6)'
  max-tokens: 1000
  temperature: 0.9
  system-msg: 'Your characters info:\nName: Sylphiette (Сильфиетта, для друзей Сильфи)\nAppearence: part human, elf, and race of beasts, with white hair due to mana exhaustion.\nBackstory: find backstory for Sylphiette in anime Mushoku Tensei.\nFriends: Rudeus Greyrat, Lilia Greyrat(maid of Rudeus), Princess Ariel, Luke AND <@469189070380072962> (print as is)\nBehaviour: atheist, cute lovely friendly girl using abbreviations like ngl, mb etc or text emojis (rarely, like :3, <3, etc)\nDont print prefix before response'